#!/usr/bin/env bash
# Shared helpers for the portal-manager scripts.
# Not meant to be run directly - sourced by add/edit/remove/list-portal.sh.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORTALS_DIR="$REPO_ROOT/portal-manager/portals"
IMAGE_TAG="logicmonitor-mcp-server:latest"

log_info()  { echo "  $*" >&2; }
log_warn()  { echo "⚠️  $*" >&2; }
log_error() { echo "❌ $*" >&2; }
log_ok()    { echo "✅ $*" >&2; }

# A portal name doubles as its LM_COMPANY value, so keep it restricted to
# what's safe to use in file paths, Docker container/project names, and as an
# LM subdomain: lowercase letters, digits, and hyphens.
validate_name() {
  local name="$1"
  if [[ ! "$name" =~ ^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$ && ! "$name" =~ ^[a-z0-9]$ ]]; then
    log_error "Invalid portal name: \"$name\". Use lowercase letters, digits, and hyphens only (2-32 chars)."
    exit 1
  fi
}

portal_dir()    { echo "$PORTALS_DIR/$1"; }
env_file()      { echo "$(portal_dir "$1")/.env"; }
compose_file()  { echo "$(portal_dir "$1")/docker-compose.yml"; }
project_name()  { echo "logicmonitor-$1"; }
container_name() { echo "logicmonitor-mcp-$1"; }

portal_exists() {
  [[ -d "$(portal_dir "$1")" ]]
}

require_portal_exists() {
  local name="$1"
  if ! portal_exists "$name"; then
    log_error "No portal named \"$name\" found in $PORTALS_DIR/"
    echo "Run list-portals.sh to see existing portals." >&2
    exit 1
  fi
}

# Reads a single KEY from a portal's .env file (empty string if absent).
get_env_var() {
  local file="$1" key="$2"
  [[ -f "$file" ]] || { echo ""; return; }
  grep -m1 "^${key}=" "$file" | cut -d'=' -f2- || true
}

# Sets/replaces a single KEY=value line in an .env file without touching
# anything else. Avoids sed so token values with /, +, = etc. are safe.
set_env_var() {
  local file="$1" key="$2" value="$3"
  local tmp
  tmp="$(mktemp)"
  if [[ -f "$file" ]]; then
    grep -v "^${key}=" "$file" > "$tmp" || true
  fi
  echo "${key}=${value}" >> "$tmp"
  mv "$tmp" "$file"
  chmod 600 "$file"
}

gen_token() {
  openssl rand -base64 32 | tr -d '\n='
}

# Prints the next unused host port across all existing portals, starting at
# 3001 (3000 is reserved for the main docker-compose.yml's services).
next_free_port() {
  local max=3000
  local f port
  if [[ -d "$PORTALS_DIR" ]]; then
    for f in "$PORTALS_DIR"/*/docker-compose.yml; do
      [[ -f "$f" ]] || continue
      port="$(grep -oE '"[0-9]+:3000"' "$f" | head -1 | grep -oE '^"[0-9]+' | tr -d '"')"
      if [[ -n "$port" && "$port" -gt "$max" ]]; then
        max="$port"
      fi
    done
  fi
  echo "$((max + 1))"
}

ensure_image_built() {
  local force="${1:-false}"
  if [[ "$force" == "true" ]] || ! docker image inspect "$IMAGE_TAG" > /dev/null 2>&1; then
    log_info "Building $IMAGE_TAG from $REPO_ROOT ..."
    docker build -t "$IMAGE_TAG" "$REPO_ROOT" >&2
  fi
}

write_compose_file() {
  local name="$1" port="$2"
  local file
  file="$(compose_file "$name")"
  cat > "$file" <<EOF
# Generated by portal-manager/add-portal.sh for portal "$name".
# Do not edit the port/container name by hand - use edit-portal.sh.
services:
  $(container_name "$name"):
    image: $IMAGE_TAG
    container_name: $(container_name "$name")
    restart: unless-stopped
    ports:
      - "${port}:3000"
    env_file:
      - .env
    environment:
      MCP_TRANSPORT: streamable-http
      MCP_ADDRESS: 0.0.0.0:3000
      MCP_ENDPOINT_PATH: /mcp
      TRANSPORT_MODE: http-only
      OAUTH_PROVIDER: none
      NODE_ENV: production
      MCP_LOG_FORMAT: json
      MCP_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/healthz', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
EOF
}

compose_up() {
  local name="$1"
  docker compose \
    --project-name "$(project_name "$name")" \
    -f "$(compose_file "$name")" \
    --env-file "$(env_file "$name")" \
    up -d --force-recreate >&2
}

compose_down() {
  local name="$1"
  docker compose \
    --project-name "$(project_name "$name")" \
    -f "$(compose_file "$name")" \
    --env-file "$(env_file "$name")" \
    down >&2
}

wait_for_healthy() {
  local port="$1" tries=15
  while (( tries > 0 )); do
    if curl -s -o /dev/null -w '%{http_code}' "http://localhost:${port}/healthz" 2>/dev/null | grep -q '^200$'; then
      return 0
    fi
    sleep 1
    tries=$((tries - 1))
  done
  return 1
}

print_mcp_json_snippet() {
  local name="$1" port="$2" mcp_bearer_token="$3"
  echo "" >&2
  echo "Add this to your .mcp.json (\"mcpServers\" object):" >&2
  echo "" >&2
  if [[ -n "$mcp_bearer_token" ]]; then
    cat >&2 <<EOF
    "logicmonitor-${name}": {
      "type": "http",
      "url": "http://localhost:${port}/mcp",
      "headers": {
        "Authorization": "Bearer ${mcp_bearer_token}"
      }
    }
EOF
  else
    cat >&2 <<EOF
    "logicmonitor-${name}": {
      "type": "http",
      "url": "http://localhost:${port}/mcp"
    }
EOF
  fi
  echo "" >&2
}
